import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import './globals.css'
import { cn } from '@/lib/utils'
import ConvexClientProvider from '@/shared/providers/convex-client-provider'
import JotaiProvider from '@/shared/providers/jotai-provider'
import { ThemeProvider } from '@/shared/providers/theme-provider'
import Header from '@/components/shared/header/header'
import Footer from '@/components/shared/footer/footer'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={cn(
            'min-h-screen bg-background font-sans antialiased relative',
            fontSans.variable
          )}
        >
          <JotaiProvider>
            <ThemeProvider>
              <ConvexClientProvider>
                <div className="pb-36">
                  <Header />
                  <div className="container pt-6 mb-36">{children}</div>
                </div>
                <Footer />
              </ConvexClientProvider>
            </ThemeProvider>
          </JotaiProvider>
        </div>
      </body>
    </html>
  )
}
